# Generated by Django 3.0.6 on 2020-05-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('martial_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorce', 'Divorce'), ('widowed', 'Widowed')], max_length=50)),
                ('age', models.IntegerField()),
                ('education_level', models.CharField(choices=[('below matric', 'Below Matric'), ('matriculate', 'Matriculate'), ('12 pass', '12 Pass'), ('graduate', 'Graduate'), ('pg', 'PG'), ('ph.d', 'Ph.D')], max_length=50)),
                ('occupation_status', models.CharField(choices=[('student', 'Student'), ('govt. employee', 'Govt. Employee'), ('unemployed', 'Unemployed'), ('self-employed', 'Self-Employed'), ('cultivator', 'Cultivator'), ('pvt. employee', 'Pvt. Employee'), ('minial job', 'Minial Job'), ('others', 'Others')], max_length=50)),
                ('income', models.CharField(choices=[('nill', 'Nill'), ('below ₹10k', 'Below ₹10k'), ('₹10k to ₹25k', '₹10k to ₹25k'), ('₹25k to ₹50k', '₹25k to ₹50k'), ('above ₹50k', 'Above ₹50k')], max_length=50)),
                ('house_no', models.IntegerField()),
                ('registered_voter', models.BooleanField(default=False)),
                ('procured_certificate_available', models.BooleanField(default=False)),
                ('aadhar_card_available', models.BooleanField(default=False)),
                ('bank_account_available', models.BooleanField(default=False)),
                ('course_class', models.CharField(blank=True, max_length=50)),
                ('type_of_education_sector', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('anganwadi center', 'Anganwadi Center')], max_length=50)),
                ('education_facility_proximity', models.CharField(blank=True, choices=[('0-5', '0-5km'), ('5-10', '5-10km'), ('10+', 'Above 10km'), ('outside the state', 'Outside the state')], max_length=50)),
                ('satisfaction_of_study', models.BooleanField(blank=True, default=False)),
                ('scholarship_received', models.BooleanField(blank=True, default=False)),
                ('scholarship_name', models.CharField(blank=True, max_length=300)),
                ('drop_out', models.BooleanField(blank=True, default=False)),
                ('drop_out_reason', models.CharField(blank=True, max_length=1000)),
                ('government_designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('government_group', models.CharField(blank=True, max_length=100, verbose_name='Group/Category')),
                ('government_monthly_income', models.IntegerField(blank=True, verbose_name='Monthly Income')),
                ('private_designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('private_group', models.CharField(blank=True, max_length=100, verbose_name='Group/Category')),
                ('private_monthly_income', models.IntegerField(blank=True, verbose_name='Monthly Income')),
                ('own_agriculture_land', models.BooleanField()),
                ('size_of_land', models.CharField(blank=True, max_length=100)),
                ('purpose_of_land', models.CharField(blank=True, max_length=1000)),
                ('profit', models.IntegerField(blank=True, verbose_name='Profit from the agriculture land')),
                ('farm_type', models.CharField(blank=True, choices=[('poultry', 'Poultry'), ('live stock', 'Live Stock'), ('others', 'others')], max_length=20)),
                ('farm_remark', models.CharField(blank=True, max_length=1000, verbose_name='Remarks, If any?')),
                ('business_type', models.CharField(blank=True, choices=[('whole sale', 'Whole Sale'), ('retail shop', 'Retail Shop'), ('others', 'others')], max_length=20)),
                ('business_remark', models.CharField(blank=True, max_length=1000, verbose_name='Remarks, If any?')),
                ('type_of_entreprenureship', models.CharField(blank=True, max_length=1000)),
                ('Entreprenureship_remark', models.CharField(blank=True, max_length=1000, verbose_name='Remarks, If any?')),
            ],
        ),
    ]
