# Generated by Django 3.0.6 on 2020-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Entreprenureship_remark',
            new_name='entreprenureship_remark',
        ),
        migrations.AlterField(
            model_name='person',
            name='government_monthly_income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monthly Income'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_monthly_income',
            field=models.IntegerField(blank=True, default=0, verbose_name='Monthly Income'),
        ),
    ]
