# Generated by Django 3.0.6 on 2020-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_auto_20200510_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='government_monthly_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monthly Income'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profit',
            field=models.IntegerField(blank=True, default=0, verbose_name='Profit from the agriculture land'),
        ),
    ]
