# Generated by Django 3.0.6 on 2020-05-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_differentlyableperson_haji_housing_oldagedperson_orphan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='differentlyableperson',
            old_name='scemes',
            new_name='schemes',
        ),
        migrations.RenameField(
            model_name='haji',
            old_name='scemes',
            new_name='schemes',
        ),
        migrations.RenameField(
            model_name='housing',
            old_name='housing_scemes',
            new_name='housing_schemes',
        ),
        migrations.RenameField(
            model_name='housing',
            old_name='specify_housing_scemes',
            new_name='specify_housing_schemes',
        ),
        migrations.RenameField(
            model_name='oldagedperson',
            old_name='scemes',
            new_name='schemes',
        ),
        migrations.RenameField(
            model_name='orphan',
            old_name='scemes',
            new_name='schemes',
        ),
    ]
