# Generated by Django 3.0.6 on 2020-05-11 15:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0005_auto_20200511_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='family_type',
            field=models.CharField(choices=[('joint family', 'Joint Family'), ('nuclear family', 'Nuclear Family'), ('extended family', 'Extended Family')], max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='fuel_for_cooking',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('firewood', 'Firewood'), ('lpg', 'LPG'), ('electricity', 'Electricity'), ('kerosene', 'Kerosene')], max_length=33),
        ),
        migrations.AlterField(
            model_name='housing',
            name='no_of_years_stayed_here',
            field=models.CharField(choices=[('since birth', 'Since Birth'), ('<10', 'Less than 10 years'), ('<25', 'Less than 25 years'), ('<50', 'Less than 50 years'), ('<70', 'Less than 70 years'), ('>70', 'Above 70 years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='housing',
            name='ownership',
            field=models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='toilet_facility',
            field=models.CharField(choices=[('open', 'Open'), ('outlet', 'Outlet'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='type_of_house',
            field=models.CharField(choices=[('pucca', 'Pucca'), ('semi pucca', 'Semi Pucca'), ('kutcha', 'Kutcha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='water_availability',
            field=models.CharField(choices=[('less than 1km', 'Less than 1km'), ('more than 1km', 'More than 1km')], max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='water_source',
            field=models.CharField(choices=[('pipe', 'Pipe'), ('river', 'River'), ('handpump', 'Handpump'), ('common pond', 'Common Pond'), ('own pond', 'Own Pond'), ('others', 'Others')], max_length=100),
        ),
    ]
